### PR TITLE
Adding new countries to IBAN list

### PR DESCRIPTION
**Pull request by tatiana-scda**
The list has been updated in 2022.
Reference: https://www.iso13616.org/

Under the file iban-registery, we can see the following missing countries and their IBANs, added into the tests:

image

image

image

image

### CODE REVIEW

**Comment by garydgregory** [comment]
@tatiana-scda 
You must have not run the tests as this PR fails the build. Run `mvn` before pushing a PR please.

**Comment by tatiana-scda** [comment]
@garydgregory  Locally validated, should be okay now

**Comment by tatiana-scda** [comment]
hey @garydgregory can we retry the workflows?

**Comment by garydgregory** [comment]
@tatiana-scda 
Rebase on master and push.

**Comment by tatiana-scda** [comment]
@garydgregory  already up to date 👍🏿

**Comment by garydgregory** [comment]
Hi @tatiana-scda 
Please rebase on git master and check what might still be missing. TY!

**Comment by garydgregory** [comment]
@tatiana-scda 
FYI, I resolved the conflict.

**Pull request merged**
