### PR TITLE
VALIDATOR-390: remove FastHashMap and replace with ConcurrentHashMap

### PR DESCRIPTION
**Pull request by LoreScianatico**

### CODE REVIEW

**Comment by garydgregory** [comment]
@LoreScianatico 
-1: Don't break binary compatibility.

**Comment by LoreScianatico** [comment]
> @LoreScianatico -1: Don't break binary compatibility.

How do I check binary compatibility?

**Comment by garydgregory** [comment]
> > @LoreScianatico -1: Don't break binary compatibility.
> 
> How do I check binary compatibility?

You have to know the Java language, or let this build check for you, in this case, a break of BC will cause the build to fail.
Please see also https://garygregory.wordpress.com/2020/06/14/how-we-handle-binary-compatibility-at-apache-commons/

**Comment by garydgregory** [comment]
> How can we get rid of FastHashMap? It's not even present in newest commons-collections

You can't "get rid" of it within a minor release.

A major release can choose to break BC, which then comes along with a change in package name and Maven coordinates.

**Comment by LoreScianatico** [comment]
Ok, this is clear (and useful). Is there any plan for a major release?

**Comment by garydgregory** [comment]
> Ok, this is clear (and useful). Is there any plan for a major release?

Not yet, there are other Apache Commons components that need attention first.

**Comment by LoreScianatico** [comment]
> > Ok, this is clear (and useful). Is there any plan for a major release?
> 
> Not yet, there are other Apache Commons components that need attention first.

All right... I guess beanutils is one of those components. Is there any roadmap where I can pick stuff to contribute?

**Comment by garydgregory** [comment]
> > > Ok, this is clear (and useful). Is there any plan for a major release?
> > 
> > 
> > Not yet, there are other Apache Commons components that need attention first.
> 
> All right... I guess beanutils is one of those components. Is there any roadmap where I can pick stuff to contribute?

There is no Commons-wide roadmap, it's what you can see on the developer's mailing list.

**Pull request closed without merging**
