### PR TITLE
supporting emails and URL's domain with underscore

### PR DESCRIPTION
**Pull request by nykolaslima**
Rebased to trunk. See #2

### CODE REVIEW

**Comment by nykolaslima** [comment]
@britter this PR was created based on current `trunk`

**Comment by britter** [comment]
Here is the JIRA ticket for this issue: https://issues.apache.org/jira/browse/VALIDATOR-358

**Comment by britter** [comment]
@nykolaslima this commit has been reverted, because of a veto on the dev ML. See http://markmail.org/message/iqddbsdkmsrd2dqe and the discussion following that message. You can subscribe to our [mailing lists](http://commons.apache.org/mail-lists.html) to join the discussion.

**Comment by nykolaslima** [comment]
@britter thank you for the followup. I agree you you guys.

**Pull request closed without merging**
