### PR TITLE
Add validator for UUIDs

### PR DESCRIPTION
**Pull request by dheid**
Hi @garydgregory !

A lot of times I need to check the validity of incoming parameters and use the Commons Validator library. Thanks for that!

Since I validate UUIDs a lot of times, I wanted to contribute a thoughtful and fast UUID check to Commons Validator. It would be so kind if you could include this.

Thank you very much!

Daniel

### CODE REVIEW

**Review by sheelprabhakar — COMMENTED** [review]
Looks good to me

**Comment by dheid** [comment]
Very cool @sheelprabhakar ! What are the next steps? Will someone merge this PR?

**Comment by garydgregory** [comment]
I will review this by thelis weekend.

**Comment by dheid** [comment]
@garydgregory So cool, thank you very much!

**Comment by dheid** [comment]
@garydgregory Okay, if your opinion and understanding of tests is a problem and you don't want additional validators, then I'll close this PR.

**Comment by benrhine** [comment]
So we're just going to let this die? Ive been looking for basically this to allow an annotation based validation of UUID parameters or at a minimum a nice concise way to somehow say isValid outside of just a parsing exception. IMHO the reason this is necessary is there are places it would be better to have validation rather than just parse errors.

**Comment by dheid** [comment]
> So we're just going to let this die? Ive been looking for basically this to allow an annotation based validation of UUID parameters or at a minimum a nice concise way to somehow say isValid outside of just a parsing exception. IMHO the reason this is necessary is there are places it would be better to have validation rather than just parse errors.

Hi @benrhine ! The folks from Hibernate Validators were able to read my tests without problems, liked my implementation and merged it into the new version. It will go into version 8.0.0 https://github.com/hibernate/hibernate-validator/pull/1199

**Comment by dermoritz** [comment]
sad about seeing this closed :-(. So to validate a string to be an UUID in Java still needs to copy paste the regex around? pulling hibernate seems to be a bad option

**Comment by ecki** [comment]
From my point offside the test coverage looks fine and while it is a bit unusual it’s easy to read and allows for good error messages. So if nothing else speaks against it, i will merge it.

**Comment by alexjferreiraml** [comment]
> From my point off view the test coverage looks fine and while it is a bit unusual it’s easy to read and allows for good error messages. So if nothing else speaks against it, i will merge it.

So, is it merged?

**Pull request closed without merging**
